version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ecommerce_db
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql/postgres_setup.sql:/docker-entrypoint-initdb.d/postgres_setup.sql
    networks:
      - data-network

  spark-master:
    build: .
    container_name: spark_master
    # Command to start Master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=ecommerce_db
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - data-network

  spark-worker:
    build: .
    container_name: spark_worker
    # Command to start Worker and point to Master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=ecommerce_db
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - data-network

  archiver:
    build: .
    container_name: file_archiver
    # Run the python archiver script
    command: python3 /app/src/archiver.py
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=ecommerce_db
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - INPUT_DIR=/app/data/input
      - ARCHIVE_DIR=/app/data/archive
      - ARCHIVE_AGE_MINUTES=1
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - data-network

networks:
  data-network:
    driver: bridge

volumes:
  pg_data:
